#!/bin/bash

# Create a resource group.
az group create --name myResourceGroup --location westcentralus

# Create a virtual network.
az network vnet create --resource-group myResourceGroup --name myVnet --subnet-name mySubnet

# Create a public IP address.
az network public-ip create --resource-group myResourceGroup --name myPublicIP

# Create a network security group.
az network nsg create --resource-group myResourceGroup --name myNetworkSecurityGroup

# Create a virtual network card and associate with public IP address and NSG.
az network nic create \
  --resource-group myResourceGroup \
  --name myNic \
  --vnet-name myVnet \
  --subnet mySubnet \
  --network-security-group myNetworkSecurityGroup \
  --public-ip-address myPublicIP

# Create a new virtual machine, this creates SSH keys if not present.
#az vm create -n VM1 -g myResourceGroup --image UbuntuLTS --vnet-name myVnet --name myNic --subnet mySubnet --public-ip-address-dns-name molodoria --ssh-key-value ""
az vm create -n VM1 -g myResourceGroup --image UbuntuLTS  --vnet-name myVnet --subnet mySubnet  --public-ip-address-dns-name molodoria --ssh-key-value ""
# Open port 80 to allow SSH traffic to host.
az vm open-port --port 80 --resource-group myResourceGroup --name VM1 --priority 101

# Use CustomScript extension to install NGINX.
az vm extension set \
  --publisher Microsoft.Azure.Extensions \
  --version 2.0 \
  --name CustomScript \
  --vm-name VM1 \
  --resource-group myResourceGroup \
  --settings '{"commandToExecute":"apt-get -y update && apt-get -y install nginx"}'
